version: "3.7"
services:
  database:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=aims
      - MONGO_INITDB_DATABASE=Robo
      - MONGO_INITDB_USERNAME=aims
      - MONGO_INITDB_PASSWORD=aims
    volumes:
      - ./database:/data/db